"""
METplus processing of iris cubes.

METplus configuration can be provided via a config file or as a python dictionary.

The following variables will be injected by CSET and can be used in the configuration file:

    * ``{CSET_INPUT_DIR}`` - The directory containing input data
    * ``{CSET_INPUT_TEMPLATE}`` - The file name of the cube in the input directory
    * ``{CSET_INPUT_NAME}`` - The name of the variable in the cube
    * ``{VALID_BEG}``, ``{VALID_END}``, ``{VALID_INCREMENT}`` - The valid time range of the cube
    * ``{INIT_BEG}``, ``{INIT_END}``, ``{INIT_INCREMENT}`` - The initialization time range of the cube
    * ``{LEAD_SEQ}`` - The lead time range of the cube
    * ``{OUTPUT_BASE}`` - The base name for the output files generated by METplus

Files written under ``{OUTPUT_BASE}`` will be collected into the output of the METplus operator.
"""

import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any
from pandas import DataFrame
import shlex
import logging
import iris
from iris.cube import Cube, CubeList
import pandas

log = logging.getLogger(__name__)

def write_metplus_config(config: dict[str, Any], filename: str | Path) -> None:
    """
    Write a METplus configuration dictionary to a file.

    Arguments:
    ----------
    config : dict[str, Any]
        The METplus configuration as a dictionary.
    filename : str|Path
        The path to the output configuration file.
    """
    log.info("Writing METplus configuration to %s", filename)
    for k,v in config.items():
        log.info("\t%s = %s", k, v)
    with open(filename, "w") as f:
        f.write("[config]\n")
        f.writelines(f"{key} = {value}\n" for key, value in config.items())


class MetplusOutput:
    """
    Holds MetPlus output data.
    """
    def __init__(self, path: Path|None = None):
        self.data: dict[str, DataFrame] = {}

        if path is not None:
            self.load_stat(path)

    def load_stat(self, path: Path):
        """
        Load the MET input data.

        Arguments:
        ----------
        path : Path
            The path to the MET input data.
        """
        for file in path.glob("*.txt"):
            data = pandas.read_csv(file, sep="\s+")
            for line_type, group in data.groupby("LINE_TYPE"):
                assert isinstance(line_type, str)
                self.data[line_type] = group

    def save(self, path: Path):
        """
        Save the MET output data.

        Arguments:
        ----------
        path : Path
            The path to save the output data.
        """
        pass

    def __getitem__(self, key: str):
        return self.data[key]


class MetplusError(Exception):
    pass


class MetplusRunner:
    def __init__(
        self,
        config_file: str | Path | None = None,
        config: dict[str, str] | None = None,
    ):
        self.config_file = config_file

        if config is None:
            config = {}

        self.config = config

        self._check_arguments()

    def _check_arguments(self):
        if self.config_file is None and len(self.config) == 0:
            raise MetplusError("Either config_file or config must be provided.")

    def run(self, cube: Cube) -> MetplusOutput:
        """
        Run the METplus processing on the given cube and return the results.

        Arguments:
        ----------
        cube : iris.cube.Cube
            The input cube to be processed by METplus.

        Returns
        -------
        MetplusOutput
            The output of the METplus processing.
        """
        with TemporaryDirectory() as temp_dir:
            work_dir = Path(temp_dir)
            self._run_metplus_command(cube, work_dir)
            return MetplusOutput(work_dir/"output")

    def generate_default_config(self, cube: Cube) -> dict[str, str]:
        """
        Generate the default METplus configuration.

        These values can be overridden by the user-provided configuration.

        Returns
        -------
        dict[str, str]
            The generated METplus configuration.
        """
        config: dict[str,str] = {}

        time_fmt = "%Y%m%dT%H%MZ"
        config["INIT_TIME_FMT"] = time_fmt
        config["VALID_TIME_FMT"] = time_fmt

        time = cube.coord('time')

        try:
            ref_time = cube.coord("forecast_reference_time")[0]
        except iris.exceptions.CoordinateNotFoundError:
            ref_time = None
        
        config["VALID_BEG"] = time.cell(0).point.strftime(time_fmt)
        config["VALID_END"] = time.cell(-1).point.strftime(time_fmt)
        config["VALID_INCREMENT"] = "1H"

        if ref_time is not None:
            # We have a reference initial time
            config["LOOP_BY"] = "INIT"

            config["INIT_BEG"] = ref_time.cell(0).point.strftime(time_fmt)
            config["INIT_END"] = ref_time.cell(0).point.strftime(time_fmt)
            config["INIT_INCREMENT"] = "1H"

            leads = [c.point - ref_time.cell(0).point for c in time.cells()]
            config["LEAD_SEQ"] = ", ".join(f"{int(l.total_seconds())}S" for l in leads)
        else:
            config["LOOP_BY"] = "VALID"
            config["LEAD_SEQ"] = "0S"

        config["FCST_VAR1_NAME"] = str(cube.var_name)

        levels = [r"{valid?fmt=%Y%m%d_%H%M%S}", *["*" for _ in range(cube.ndim - 1)]]

        config["FCST_VAR1_LEVELS"] = f"({','.join(levels)})"
        print(config)
        return config

    def generate_override_config(self) -> dict[str, str]:
        """
        Generate the override METplus configuration.

        These values override the user-provided configuration.

        Returns
        -------
        dict[str, str]
            The generated METplus configuration.
        """
        config: dict[str,str] = {}
        return config

    def _run_metplus_command(self, cube: Cube, work_dir: Path):
        """
        Run the METplus command with the given input file and output base.

        Arguments:
        ----------
        cube : iris.cube.Cube
            The input cube to be processed by METplus.
        work_dir : Path
            The working directory containing the output files generated by METplus.
        """
        # Save the cube to a temporary NetCDF file
        input_file = work_dir / "input.nc"
        iris.save(cube, input_file)

        default_config = self.generate_default_config(cube)
        default_config_file = work_dir / "default.conf"
        write_metplus_config(default_config, default_config_file)

        override_config = self.generate_override_config()
        override_config["CSET_INPUT_DIR"] = str(work_dir)
        override_config["CSET_INPUT_TEMPLATE"] = input_file.name
        override_config["OUTPUT_BASE"] = str(work_dir / "output")
        override_config["LOG_METPLUS"] = str(work_dir / "metplus.log")

        override_config_file = work_dir / "override.conf"
        write_metplus_config(override_config, override_config_file)

        config_file = work_dir / "config.conf"
        write_metplus_config(self.config, config_file)

        cmd = ["run_metplus"]
        cmd.append(str(default_config_file))
        if self.config_file is not None:
            cmd.append(str(self.config_file))
        cmd.append(str(config_file))
        cmd.append(str(override_config_file))

        log.info(f"Running METplus command: {shlex.join(cmd)}")
        try:
            subprocess.run(cmd, check=True)
            with open(work_dir / "metplus.log", "r") as log_file:
                log.warning(log_file.read())
        except subprocess.CalledProcessError as e:
            log.error(f"METplus command failed with error: {e}")
            with open(work_dir / "metplus.log", "r") as log_file:
                log.error(log_file.read())
            raise


class PointStatRunner(MetplusRunner):
    def generate_default_config(self, cube: Cube) -> dict[str, Any]:
        config = super().generate_default_config(cube)
        config["PROCESS_LIST"] = "PointStat"
        config["FCST_POINT_STAT_INPUT_DIR"] = "{CSET_INPUT_DIR}"
        config["FCST_POINT_STAT_INPUT_TEMPLATE"] = "{CSET_INPUT_TEMPLATE}"
        config["POINT_STAT_OUTPUT_FLAG_CNT"] = "BOTH"
        return config

    def generate_override_config(self) -> dict[str, Any]:
        config = super().generate_override_config()
        config["POINT_STAT_OUTPUT_DIR"] = "{OUTPUT_BASE}"
        return config
